added sign in button to the side bar
misghna/holy-ui pull request #26
Opened 2024-04-29 18:08 UTC by siru-kid

signin button added to the bottom of side bar menu

2024-05-05 15:01 UTC, kuldep7 requested changes

2024-05-05 15:01 UTC, kuldep7 commented on src/components/Drawer.jsx
> +            <StyledCustomButtons onClick={() => handleNavigation("/logout")} color="primary">
I don't think we will have a logout page to redirect to
So here you can pass the callType like login or logout and in handleNavigation function you can have a switch case for the received type and perform need action form there

2024-05-06 08:17 UTC, siru-kid commented on src/components/Drawer.jsx
>    const [isSubMenOpen, setIsSubMenOpen] = useState([...submenus]);
okay i'm changing it to --> const [subMenuOpenState, setSubMenuOpenState] = useState([...subMenuOpenStateInitial]);
#updated

2024-05-06 08:17 UTC, siru-kid commented on src/components/Drawer.jsx
> +    arr[typeIndex] = arr[typeIndex].map(() => false);
i changed to this --> newState[typeIndex] = newState[typeIndex].map(() => false);  but if there other name sugestion let me know
#updated

2024-05-06 08:17 UTC, siru-kid commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
not nothing is removed just added something to help me with styling  <IconButton onClick={handleDrawerClose}>
              {theme.direction === "ltr" ? <ChevronLeftIcon /> : <ChevronRightIcon />}
            </IconButton>
#updated

2024-05-06 17:25 UTC, kuldep7 commented on src/components/Drawer.jsx
>    const [isSubMenOpen, setIsSubMenOpen] = useState([...submenus]);
But here we have a list of submenus right I think it should convey that

2024-05-06 17:26 UTC, kuldep7 commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
OnClose and onOpen are required propa so please make sure they are there , and small note please try to resolve any console warings

2024-05-06 17:27 UTC, kuldep7 commented on src/components/Drawer.jsx
> +            <StyledCustomButtons onClick={() => handleNavigation("/logout")} color="primary">
User will be redirected to login page on logout button click or to the public home page

2024-05-07 20:08 UTC, siru-kid commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
Was the drawer previously set up to close automatically when clicked outside of it?

2024-05-09 00:22 UTC, kuldep7 commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
No ... But it will be implemented sooner or later. Its basically giving a console error and we don't want any warnings and errors in our console

2024-05-09 14:37 UTC, siru-kid commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
what about now could you let me know and the console error
 isn't from the drawer.jsx file

2024-05-09 17:19 UTC, kuldep7 commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
If possible you can add functionality to close drawer (both left and right side ) on outside click 
Regarding console errors please check and try to resolve and warnings in the console

2024-05-10 20:24 UTC, siru-kid commented on src/components/Drawer.jsx
> -      onClose={handleDrawerClose}
So I implemented the sidebar outside click close functionality! but sorry i couldn't figure out console error

2024-05-11 16:50 UTC, closed without merging