Feature/drawer
misghna/holy-ui pull request #5
Opened 2024-03-27 18:55 UTC by davewish

2024-03-30 14:01 UTC, kuldep7 commented on src/contexts/SettingProvider.jsx
> +import PropTypes from "prop-types";
Please check AuthContext file to follow,
basically no nee to separate context and provider

2024-03-30 14:04 UTC, kuldep7 requested changes

2024-03-30 14:04 UTC, kuldep7 commented on src/hooks/useSetting.js
> +      dispatch({ type: actionTypes.FETCH_SUCCESS, payload: response?.data });
for apis please check useGridData changes by me
we need to use "/api" now as base

2024-03-30 14:04 UTC, kuldep7 commented on src/contexts/SettingProvider.jsx
> +  ) : null;
Please check AuthContext file to follow,
basically no need to separate context and provider
and in context folder please use PascalCase naming and only have XyzContext namings

2024-04-02 14:55 UTC, kuldep7 requested changes

2024-04-02 14:55 UTC, kuldep7 commented on src/contexts/LayoutProvider.jsx
> +export const LayoutContext = createContext({ state: { open: false }, dispatch: () => {} });
no need to export context as such like we can create a hook for this context , please refer AuthProvider file

2024-04-03 11:05 UTC, misghna commented on src/constants/endpoints.json
I would rename 
setting to globalSettings
GridData to contentData

2024-04-03 11:07 UTC, davewish commented on src/constants/endpoints.json
okay

2024-04-04 02:09 UTC, merged